### ISSUE TITLE
Date dropdown list does not work on Firefox

### ISSUE THREAD

**Issue by FFrancieli** [tw-agendador/agendador#39] opened 2015-07-01 14:50 UTC
It's not possible to use the drop down list to pick a date on Firefox. The dropdown list should be able to the user when the field is under focus.
See image below:
![screen shot 2015-07-01 at 11 45 48](https://cloud.githubusercontent.com/assets/5590513/8457298/efbeacda-1fe6-11e5-98e4-a45252f749fd.png)

The same field (when focused) on Chrome:
![screen shot 2015-07-01 at 11 48 42](https://cloud.githubusercontent.com/assets/5590513/8457356/45e679c6-1fe7-11e5-94bd-f10952608d5f.png)

**Comment by lucastfa** [comment] 2015-07-24 17:47
When changing the date quickly the calendar is freezing and messing the day display.

**Comment by gama** [comment] 2015-08-03 13:27
I was unable to reproduce this, so I'll close it for now.

**Closed** 2015-08-03 13:27 UTC
Labels: bug
